[common]
script_location = migrations/common
prepend_sys_path = .
[cases]
script_location = migrations/cases
prepend_sys_path = .
[compliance]
script_location = migrations/compliance
prepend_sys_path = .
