appname = casdoor
httpport = 8000
runmode = prod
copyrequestbody = true
driverName = postgres
dbName = casdoor
showSql = false
isDemoMode = false
defaultLanguage = zh
defaultApplication = compliance-evaluation
enableGzip = true
initDataNewOnly = true
initDataFile = /conf/init_data.json
frontendBaseDir = /web/build
